name: er-save-editor-release

run-name: Publishing a new release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build --release

      - name: Package binaries
        run: |
          mkdir -p dist
          cp target/release/Er-Save-Editor.exe dist/
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Er-Save-Editor.exe
